# Generated by Django 2.2.5 on 2020-08-24 21:37

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200825_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=markdownx.models.MarkdownxField(null=True, verbose_name='CONTENT'),
        ),
    ]
