# Generated by Django 2.2.5 on 2020-07-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortFolioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(null=True)),
                ('skills', models.CharField(max_length=140)),
                ('period', models.IntegerField(default=1)),
                ('linked', models.URLField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
