# Generated by Django 2.2.5 on 2020-08-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_auto_20200729_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Types'},
        ),
    ]
