# Generated by Django 2.2.5 on 2020-08-13 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_auto_20200802_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('caption', models.CharField(max_length=80)),
                ('file', models.ImageField(upload_to='')),
                ('PortFolioModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolios.PortFolioModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
