# Generated by Django 2.2.5 on 2020-08-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0004_auto_20200802_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=140)),
                ('portfolio', models.ManyToManyField(blank=True, to='portfolios.PortFolioModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
